# Generated by Django 5.2.10 on 2026-01-09 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicao',
            options={'ordering': ['-registrada_em'], 'verbose_name': 'Medição', 'verbose_name_plural': 'Medições'},
        ),
    ]
