# Generated by Django 5.0.5 on 2026-01-15 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicoes', '0002_alter_medicao_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicao',
            name='profundidade',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
