# Generated by Django 5.0.13 on 2026-01-18 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_aparelho'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aparelho',
            options={'verbose_name': 'Aparelho', 'verbose_name_plural': 'Aparelhos'},
        ),
        migrations.AddField(
            model_name='aparelho',
            name='mac_address',
            field=models.CharField(blank=True, help_text='Endereço MAC do hardware (Ex: AA:BB:CC:11:22:33)', max_length=17, null=True, unique=True),
        ),
    ]
