# Generated by Django 5.0.13 on 2026-01-18 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_aparelho_options_aparelho_mac_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='aparelho',
            name='temp_max',
            field=models.FloatField(default=8.0, help_text='Temperatura máxima aceitável'),
        ),
        migrations.AddField(
            model_name='aparelho',
            name='temp_min',
            field=models.FloatField(default=2.0, help_text='Temperatura mínima aceitável'),
        ),
    ]
