# Generated by Django 5.0.13 on 2026-01-18 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_aparelho_temp_max_aparelho_temp_min'),
    ]

    operations = [
        migrations.AddField(
            model_name='aparelho',
            name='ultima_comunicacao',
            field=models.DateTimeField(blank=True, help_text='Último sinal recebido do ESP32', null=True),
        ),
    ]
