# Generated by Django 5.2.9 on 2025-12-18 01:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Sensor identifier name', max_length=100)),
                ('code', models.CharField(help_text='Unique sensor code (e.g., ESP32-001)', max_length=50, unique=True)),
                ('description', models.TextField(blank=True, help_text='Sensor description', null=True)),
                ('store_id', models.IntegerField(blank=True, help_text='Store ID where the sensor is installed (temporary until stores app is created)', null=True)),
                ('min_temperature', models.FloatField(default=-10.0, help_text='Minimum acceptable temperature in °C', validators=[django.core.validators.MinValueValidator(-50.0), django.core.validators.MaxValueValidator(50.0)])),
                ('max_temperature', models.FloatField(default=10.0, help_text='Maximum acceptable temperature in °C', validators=[django.core.validators.MinValueValidator(-50.0), django.core.validators.MaxValueValidator(50.0)])),
                ('is_active', models.BooleanField(default=True, help_text='Is sensor active?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device_type', models.CharField(default='ESP32', help_text='Device type (ESP32, ESP8266, etc.)', max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Device IP address', null=True)),
            ],
            options={
                'verbose_name': 'Sensor',
                'verbose_name_plural': 'Sensors',
                'db_table': 'sensors',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['code'], name='sensors_code_21e07f_idx'), models.Index(fields=['is_active'], name='sensors_is_acti_9fc02d_idx'), models.Index(fields=['store_id'], name='sensors_store_i_539ca0_idx')],
            },
        ),
    ]
