# Generated by Django 5.0.13 on 2026-01-18 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alertas', '0002_alertalog'),
        ('core', '0003_alter_aparelho_options_aparelho_mac_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerta',
            name='aparelho',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='core.aparelho'),
        ),
    ]
